/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kisan.seva.kiosk;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author Prabhat
 */
public class finalsubmission extends javax.swing.JFrame {
    String a1[]=new String[9];
    String a2[]=new String[8];
    String a3[]=new String[8];
    String a4[]=new String[5];
    /**
     * Creates new form finalsubmission
     */
    public finalsubmission() {
        initComponents();
        setExtendedState(profile.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }
    public finalsubmission(String a[],String b[],String c[],String d[]) {
        initComponents();
        setExtendedState(profile.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        a1=a;
        a2=b;
        a3=c;
        a4=d;
        DefaultTableModel model=(DefaultTableModel)t1.getModel();
        model.setRowCount(0);
        model.addRow(new Object[]{
                "FULL NAME",a1[1]
                    });
        model.addRow(new Object[]{
                "MARRIED STATUS",a1[2]
                    });model.addRow(new Object[]{
                "CATEGORY",a1[3]
                    });model.addRow(new Object[]{
                "PHONE NUMBER",a1[4]
                    });model.addRow(new Object[]{
                "STATE",a1[5]
                    });
                    model.addRow(new Object[]{
                "DISTRICT",a1[6]
                    });
                    model.addRow(new Object[]{
                "VILLAGE",a1[7]
                    });
                    model.addRow(new Object[]{
                "ADRESS",a1[8]
                    });
               model.addRow(new Object[]{
                "AADHAR NUMBER",a2[0]
                    });
        model.addRow(new Object[]{
                "BANK ACCOUNT NUMBER",a2[1]
                    });model.addRow(new Object[]{
                "NAME OF THE BANK",a2[2]
                    });model.addRow(new Object[]{
                "BRANCH NAME",a2[3]
                    });model.addRow(new Object[]{
                "IFSC CODE",a2[4]
                    });
                    model.addRow(new Object[]{
                "PAN CARD",a2[5]
                    });
                    model.addRow(new Object[]{
                "VOTER ID",a2[6]
                    });  
                    model.addRow(new Object[]{
                "LPG NUMBER",a2[7]
                    }); 
                    model.addRow(new Object[]{
                "WIFE/HUSBAND NAME",a3[0]
                    }); 
                    model.addRow(new Object[]{
                "NOMINEE OF THIS ACCOUNT",a3[1]
                    });
                    model.addRow(new Object[]{
                "AADHAR CARD",a3[2]
                    });
                    model.addRow(new Object[]{
                "RELATION TYPE",a3[3]
                    });
                    model.addRow(new Object[]{
                "EDUCATION QUALIFICATION",a3[4]
                    });
                   model.addRow(new Object[]{
                "OWNER NAME",a4[0]
                    }); 
                   model.addRow(new Object[]{
                "REGISTRATION NUMBER",a4[1]
                    }); 
              model.addRow(new Object[]{
                "NAME OF THE LAND NOMINEE",a4[2]
                    });
              
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1.setFont(new java.awt.Font("Lao Sangam MN", 0, 14)); // NOI18N
        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(t1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 570, 430));

        jLabel3.setFont(new java.awt.Font("Lao Sangam MN", 0, 24)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kisan/seva/kiosk/Header.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, 0, 1420, 140));

        jButton2.setFont(new java.awt.Font("Lao Sangam MN", 0, 13)); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 660, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new start().setVisible(true);
       this.setVisible(false); 
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(finalsubmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(finalsubmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(finalsubmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(finalsubmission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new finalsubmission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t1;
    // End of variables declaration//GEN-END:variables
}
