/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kisan.seva.kiosk;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prabhat
 */
public class myprofile extends javax.swing.JFrame {
String a1[]=new String[10];
String b[]=new String[30];
    /**
     * Creates new form myprofile
     */
    public myprofile() {
        initComponents();
    }
    public myprofile(String a[],String a2[]) {
        initComponents();
        a1=a;
        b=a2;
        setExtendedState(profile.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
        DefaultTableModel model=(DefaultTableModel)t1.getModel();
        model.setRowCount(0);
        model.addRow(new Object[]{
                "FULL NAME",a2[0]
                    });
        model.addRow(new Object[]{
                "MARRIED STATUS",a2[1]
                    });model.addRow(new Object[]{
                "CATEGORY",a2[2]
                    });model.addRow(new Object[]{
                "PHONE NUMBER",a2[3]
                    });model.addRow(new Object[]{
                "STATE",a2[4]
                    });
                    model.addRow(new Object[]{
                "DISTRICT",a2[5]
                    });
                    model.addRow(new Object[]{
                "VILLAGE",a2[6]
                    });
                    model.addRow(new Object[]{
                "ADRESS",a2[7]
                    });
               model.addRow(new Object[]{
                "AADHAR NUMBER",a2[8]
                    });
        model.addRow(new Object[]{
                "BANK ACCOUNT NUMBER",a2[9]
                    });model.addRow(new Object[]{
                "NAME OF THE BANK",a2[10]
                    });model.addRow(new Object[]{
                "BRANCH NAME",a2[11]
                    });model.addRow(new Object[]{
                "IFSC CODE",a2[12]
                    });
                    model.addRow(new Object[]{
                "PAN CARD",a2[13]
                    });
                    model.addRow(new Object[]{
                "VOTER ID",a2[14]
                    });  
                    model.addRow(new Object[]{
                "LPG NUMBER",a2[15]
                    }); 
                    model.addRow(new Object[]{
                "WIFE/HUSBAND NAME",a2[16]
                    }); 
                    model.addRow(new Object[]{
                "NOMINEE OF THIS ACCOUNT",a2[20]
                    });
                    model.addRow(new Object[]{
                "AADHAR CARD",a2[21]
                    });
                    model.addRow(new Object[]{
                "RELATION TYPE",a2[22]
                    });
                    model.addRow(new Object[]{
                "EDUCATION QUALIFICATION",a2[23]
                    });
                   model.addRow(new Object[]{
                "OWNER NAME",a2[24]
                    }); 
                   model.addRow(new Object[]{
                "REGISTRATION NUMBER",a2[25]
                    }); 
              model.addRow(new Object[]{
                "NAME OF THE LAND NOMINEE",a2[28]
                    });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kisan/seva/kiosk/Header.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, 0, 1260, 130));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 130));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        t1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(t1);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 570, 430));
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 170, 120));

        jButton2.setText("UPDATE");
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 530, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kisan/seva/kiosk/rsz_1rsz_1rsz_1rsz_53567.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1250, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        new profile(a1,b).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(myprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new myprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable t1;
    // End of variables declaration//GEN-END:variables
}
